### ISSUE TITLE
py3?

### ISSUE THREAD

**Issue by hredestig** [alexarnimueller/modlAMP#6]
Very nice project! Unfortunately, the rest of my code base if very much py3 based - have you considered adding py3 support? Would you be interested in contributions?

**Comment by alexarnimueller** [comment]
hi hredestig, thanks!
I did not find time to migrate to python3 yet. but yes, I would be very happy to receive your contributions!

**Comment by alexarnimueller** [comment]
I have created a new branch called py3, which should mostly be python3 compatible. let me know if you find bugs in there

**Comment by hredestig** [comment]
Nice, thanks, will take a look!

**Comment by spaenigs** [comment]
Just a minor issue:  https://github.com/alexarnimueller/modlAMP/blob/e885427d57915c8de487977aebfdd20ee405f778/modlamp/descriptors.py#L961

The floats here have to be explicitly casted to integers for Python 3 support. Otherwise the code will break with the following message:

`File "/home/user/Apps/anaconda3/envs/py36/lib/python3.6/site-packages/modlamp/descriptors.py", line 961, in calculate_profile
    x_vals = range(len(seq))[((window - 1) / 2):-((window - 1) / 2)]
TypeError: slice indices must be integers or None or have an __index__ method`

Thanks for the useful package :)

**Comment by alexarnimueller** [comment]
Hi Spaenigs
Thanks for pointing that one out, we were missing a test for it as well. I've corrected the type cast and added a test for it too. new version 4.0.1 is ready to be installed
Cheers
